### ISSUE TITLE
Sketch Export Issue

### ISSUE THREAD

**Issue by fuatkestane** [smartface/sketch-export-tool#1]
Hi,

I do the operations according to the steps shown, but when I select and export the work, only the **images** folder is created within the resulting folder. Nothing else seems. I'm waiting for your help on this.

Best regards.

**Comment by Burakdemirci** [comment]
-Don't forget to change your folder visibility settings of your computer. sketch-export-tool will generate folders that are hidden such as .ui

**Comment by fuatkestane** [comment]
Thank you very much, I was able to run now. 👍
